import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Captured copies of the live site (scripts/capture-brand.mjs).
    "docs/brand/source/**",
    // OpenNext and wrangler build output. Linting it runs eslint out of memory.
    ".open-next/**",
    ".wrangler/**",
    // Generated by Payload.
    "src/app/(payload)/admin/importMap.js",
    "src/migrations/**",
  ]),
]);

export default eslintConfig;
